// <auto-generated />
using DomiWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomiWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220161832_AddArtiklAToDbAndSeed")]
    partial class AddArtiklAToDbAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomiWeb.Models.Artikl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 12m,
                            Kategorija = "Voće",
                            Naziv = "Banane"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 14m,
                            Kategorija = "Voće",
                            Naziv = "Jabuke"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 11m,
                            Kategorija = "Voće",
                            Naziv = "Kruške"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 10m,
                            Kategorija = "Povrće",
                            Naziv = "Krastavac"
                        },
                        new
                        {
                            Id = 5,
                            Cijena = 9m,
                            Kategorija = "Povrće",
                            Naziv = "Paprika"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
